Delete from amicus.T_CLSTN_TYP where TBL_VLU_CDE = '29';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '72';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '73';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '74';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '75';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '76';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '77';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '78';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '79';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '80';
Delete from amicus.T_CLSTN_FNCTN where TBL_VLU_CDE = '81';

Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4520','452','0',now(),null,'Local 990','Local 990','990 _ _ Local 990','990 _ _ Local 990');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4530','453','0',now(),null,'Local 991','Local 991','991 _ _ Local 991','991 _ _ Local 991');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4540','454','0',now(),null,'Local 992','Local 992','992 _ _ Local 992','992 _ _ Local 992');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4550','455','0',now(),null,'Local 993','Local 993','993 _ _ Local 993','993 _ _ Local 993');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4560','456','0',now(),null,'Local 994','Local 994','994 _ _ Local 994','994 _ _ Local 994');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4570','457','0',now(),null,'Local 995','Local 995','995 _ _ Local 995','995 _ _ Local 995');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4580','458','0',now(),null,'Local 996','Local 996','996 _ _ Local 996','996 _ _ Local 996');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4590','459','0',now(),null,'Local 997','Local 997','997 _ _ Local 997','997 _ _ Local 997');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4600','460','0',now(),null,'Local 998','Local 998','998 _ _ Local 998','998 _ _ Local 998');
Insert into amicus.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT)
values ('4610','461','0',now(),null,'Local 999','Local 999','999 _ _ Local 999','999 _ _ Local 999');


Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '990';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '991';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '992';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '993';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '994';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '995';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '996';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '997';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '998';
Delete from OLISUITE.S_BIB_MARC_IND_DB_CRLTN where MARC_TAG_NBR = '999';

Delete from OLISUITE.T_CLSTN_TYP where TBL_VLU_CDE = '29';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '72';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '73';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '74';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '75';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '76';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '77';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '78';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '79';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '80';
Delete from OLISUITE.T_CLSTN_FNCTN where TBL_VLU_CDE = '81';

Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('990',' ',' ','7','452','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('991',' ',' ','7','453','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('992',' ',' ','7','454','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('993',' ',' ','7','455','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('994',' ',' ','7','456','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('995',' ',' ','7','457','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('996',' ',' ','7','458','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('997',' ',' ','7','459','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('998',' ',' ','7','460','-1','-1','bn');
Insert into OLISUITE.S_BIB_MARC_IND_DB_CRLTN (MARC_TAG_NBR,MARC_TAG_1ST_IND,MARC_TAG_2ND_IND,MARC_TAG_CAT_CDE,MARC_TAG_IND_VLU_1_CDE,MARC_TAG_IND_VLU_2_CDE,MARC_TAG_IND_VLU_3_CDE,SRCH_IDX_TYP_CDE) values ('999',' ',' ','7','461','-1','-1','bn');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4520','452','0','Local 990','990 _ _ Local 990','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4520','452','0','Local 990','990 _ _ Local 990','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4530','453','0','Local 991','991 _ _ Local 991','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4530','453','0','Local 991','991 _ _ Local 991','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4540','454','0','Local 992','992 _ _ Local 992','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4540','454','0','Local 992','992 _ _ Local 992','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4550','455','0','Local 993','993 _ _ Local 993','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4550','455','0','Local 993','993 _ _ Local 993','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4560','456','0','Local 994','994 _ _ Local 994','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4560','456','0','Local 994','994 _ _ Local 994','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4570','457','0','Local 995','995 _ _ Local 995','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4570','457','0','Local 995','995 _ _ Local 995','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4580','458','0','Local 996','996 _ _ Local 996','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4580','458','0','Local 996','996 _ _ Local 996','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4590','459','0','Local 997','997 _ _ Local 997','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4590','459','0','Local 997','997 _ _ Local 997','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4600','460','0','Local 998','998 _ _ Local 998','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4600','460','0','Local 998','998 _ _ Local 998','ita');

Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4610','461','0','Local 999','999 _ _ Local 999','eng');
Insert into OLISUITE.T_BIB_NTE_TYP (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) values ('4610','461','0','Local 999','999 _ _ Local 999','ita');

Delete from amicus.IDX_LIST where IDX_LIST_ABRVT_CDE like '%LX%';

Delete from olisuite.IDX_LIST where IDX_LIST_ABRVT_CDE like '%LX%';

