Insert into OLISUITE.T_RSI_ATT_SENS (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) 
values (50,'u','0','unknown','unknown','eng');
Insert into OLISUITE.T_RSI_ATT_SENS (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,SHORT_STRING_TEXT,STRING_TEXT,LANGID) 
values (50,'u','0','sconosciuto','sconosciuto','ita');
Insert into AMICUS.T_RSI_ATT_SENS (TBL_SEQ_NBR,TBL_VLU_CDE,TBL_VLU_OBSLT_IND,TBL_VLU_ACTV_STRT_DTE,TBL_VLU_ACTV_END_DTE,TBL_SHRT_ENG_TXT,TBL_SHRT_FR_TXT,TBL_LNG_ENG_TXT,TBL_LNG_FR_TXT) 
values (50,'u','0',now(),null,'unknown','sconosciuto','unknown','sconosciuto');
