configuration:
  endpoint: http://localhost:9132
  port: 9132
  local: localhost
  baseUrl: marccat

logging:
  level:
    root: ERROR
    org.springframework: ERROR
    net.sf.hibernate: ERROR
    net.sf.hibernate.SQL: DEBUG
    org.folio.marccat.integration.search: DEBUG
    ru.yandex: ERROR
    org.folio.marccat: INFO

server:
  port: 9132
