#%RAML 0.8
title: FiTempl
version: v1
baseUri: http://github.com/org/folio/mod-cataloging

documentation:
  - title: mod-cataloging API
    content: This documents the API calls that can be made to manage field templates within the cataloging module.

schemas:
  - variableField:  !include schemas/variableField.json
  - fixedField:  !include schemas/fixedField.json
  - fieldTemplate: !include schemas/fieldTemplate.json
  - fieldTemplateCollection: !include schemas/fieldTemplateCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error.schema: !include ../raml-util/schemas/error.schema
  - parameters.schema: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - orderable: !include ../raml-util/traits/orderable.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml

/cataloging/field-template:
  type:
      collection-item:
        exampleItem: !include examples/fieldTemplate.json
        schema: fieldTemplate
  get:
    queryParameters:
      categoryCode:
        displayName: marc category
        description: the marc category code
        required: true
        type: integer
      ind1:
        displayName: First indicator
        description: First indicator
        type: string
        minLength: 1
        maxLength: 1
      ind2:
        displayName: Second indicator
        description: the second indicator
        minLength: 1
        maxLength: 1
        type: string
      code:
        displayName: tag number
        description: the tag number
        required: true
        type: string
        minLength: 3
        maxLength: 3
      headerTypeCode:
        displayName: the header type code
        description: the header type code
        type: integer
      leader:
        displayName: the leader of record
        description: the leader of record
        type: string
        minLength: 24
        maxLength: 24
      valueField:
        displayName: the value field
        description: the value field for fixed-field
        type: string





