#%RAML 0.8
title: FixedFieldsCodesGroups
version: v1
baseUri: http://github.com/org/folio/mod-cataloging

documentation:
  - title: mod-cataloging API
    content: This documents the API calls that can be made to manage fixed field codes groups within the cataloging module.

schemas:
  - recordStatusType: !include schemas/recordStatusType.json
  - recordType: !include schemas/recordType.json
  - bibliographicLevel: !include schemas/bibliographicLevel.json
  - controlType: !include schemas/controlType.json
  - characterEncodingSchema: !include schemas/characterEncodingSchema.json
  - encodingLevel: !include schemas/encodingLevel.json
  - descriptiveCatalogForm: !include schemas/descriptiveCatalogForm.json
  - dateType: !include schemas/dateType.json
  - modifiedRecordType: !include schemas/modifiedRecordType.json
  - catalogSource: !include schemas/catalogSource.json
  - fixedFieldCodesGroup: !include schemas/fixedFieldCodesGroup.json
  - fixedFieldCodesGroupCollection: !include schemas/fixedFieldCodesGroupCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error.schema: !include ../raml-util/schemas/error.schema
  - parameters.schema: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - orderable: !include ../raml-util/traits/orderable.raml
  - pageable: !include ../raml-util/traits/pageable.raml
  - searchable: !include ../raml-util/traits/searchable.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml

/cataloging/fixed-field:
  /codes-groups:
    type:
      collection-item:
        exampleItem: !include examples/fixedFieldCodesGroup.json
        schema: fixedFieldCodesGroup
    get:
      queryParameters:
        code:
          displayName: tag number of fixed-field
          description: tag number
          required: true
          type: string
        headerTypeCode:
          displayName: Header code of fixed-field
          description: the header code of fixed-field
          required: true
          type: integer
