#%RAML 0.8
title: Frbr Types
version: v1
baseUri: http://github.com/org/folio/mod-cataloging

documentation:
  - title: mod-cataloging API
    content: This documents the API calls that can be made to manage fbrb type entity.

schemas:
  - frbrType: !include schemas/frbrType.json
  - frbrTypeCollection: !include schemas/frbrTypeCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error.schema: !include ../raml-util/schemas/error.schema
  - parameters.schema: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml

/frbr-types:
  type:
    collection:
      exampleCollection: !include examples/frbrTypeCollection.json
      exampleItem: !include examples/frbrType.json
      schemaCollection: frbrTypeCollection
      schemaItem: frbrType
  /{code}:
    type:
      collection-item:
        exampleItem: !include examples/frbrType.json
        schema: frbrType
    get:
      description: Get a single frbr type
