#%RAML 0.8
title: IndexCategory
version: v1
baseUri: http://github.com/org/folio/mod-cataloging

documentation:
  - title: mod-cataloging API
    content: This documents the API calls that can be made to manage cataloging indexes categories.

schemas:
  - indexCategory: !include schemas/indexCategory.json
  - indexCategoryCollection: !include schemas/indexCategoryCollection.json
  - errors: !include ../raml-util/schemas/errors.schema
  - error.schema: !include ../raml-util/schemas/error.schema
  - parameters.schema: !include ../raml-util/schemas/parameters.schema

traits:
  - secured: !include ../raml-util/traits/auth.raml
  - language: !include ../raml-util/traits/language.raml
  - validate: !include ../raml-util/traits/validation.raml

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml

/cataloging/index-categories:
  type:
    collection:
      exampleCollection: !include examples/logicalViewCollection.json
      exampleItem: !include examples/logicalView.json
      schemaCollection: indexCategoryCollection
      schemaItem: indexCategory
  get:
    queryParameters:
      type:
        displayName: Type
        description: the category's type (either primary or secondary)
        required: true
        example: P(rimary), (S)econdary
        enum: [P,S]
        default: P