Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authority.cataloguingSourceStringText',CHR(31)||'aPS','Authority cataloguing source stringText');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authority.classification.type','12','Authority classification type');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authority.classification.function','34','Cataloguing Source StringText');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authority.reference.specialRelationship','n','Authority reference special relationship');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authorityNote.noteType','26','Authority note note type');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('authority.verificationLevel','1','Authority verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.cataloguingSourceStringText',CHR(31)||'aItFiC','BibliographicItem cataloguing source stringText');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.languageCode','eng', 'Language code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.languageOfCataloguing','it', 'Language of cataloguing');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.recordCataloguingSourceCode','r', 'Record cataloguing source code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.marcCountryCode','enk', 'Marc country code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.itemDateTypeCode','s', 'Item date type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicItem.verificationLevel','2', 'Verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicNote.noteType','50', 'Bibliographic note type');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicRelationship.relationTypeCode','35', 'Relation type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographicRelationship.relationPrintNoteCode','2', 'Relation print note code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('bibliographic.shelflist.type','@', 'Shelflist type');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.bookBiographyCode',' ', 'Material book biography code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.bookFestschrift','0', 'Material book festschrift');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.bookIllustrationCode','    ', 'Material book illustration code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.bookIndexAvailabilityCode','0', 'Material book index availability code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.bookLiteraryFormTypeCode','u', 'Material book literary form type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.cartographicFormatCode','  ', 'Material cartographic format code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.cartographicMaterial','u', 'Cartographic Material');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.cartographicProjectionCode','  ', 'Material cartographic projection code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.cartographicReliefCode','    ', 'Material cartographic relief code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.cartographicIndexAvailabilityCode','1', 'Material cartographic index availability code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.computerFileTypeCode','u', 'Material computer file type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.computerFileFormCode',' ', 'Material computer file form code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.conferencePublicationCode','0', 'Material conference publication code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.formOfItemCode',' ', 'Material form of item code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.governmentPublicationCode',' ', 'Material government publication code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicFormOfCompositionCode','uu', 'Material music form of composition code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicFormatCode','u', 'Material music format code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicLiteraryTextCode','  ', 'Material music literary text code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicTextualMaterialCode','      ', 'Material music textual material code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicPartsCode','u', 'Material music parts code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.musicTranspositionArrangementCode','u', 'Material music transposition arrangement code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.natureOfContentsCode','    ', 'Material nature of contents code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.serialFrequencyCode','u', 'Material serial frequency code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.serialOriginalAlphabetOfTitleCode',' ', 'Material serial original alphabet of title code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.serialRegularityCode','u', 'Material serial regularity code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.serialSuccessiveLatestCode','0', 'Material serial successive latest code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.serialTypeCode',' ', 'Material serial type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.targetAudienceCode',' ', 'Material target audience code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.visualMaterialTypeCode','z', 'Material visual material type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.visualRunningTime','---', 'Material visual running time');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.imageBitDepth','---', 'Material image bit depth');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.reductionRatioCode','---', 'Material reduction ratio code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.inspectionDate','||||||', 'Material inspection date');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.remoteSensingDataTypeCode','uu', 'Material remote sensing data type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.mediumForSoundCode','u', 'Material medium for sound code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.videoRecordingFormatCode','u', 'Material video recording format code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.soundOnMediumOrSeparateCode','u', 'Material sound on medium or separate code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.visualTechniqueCode','u', 'Material visual technique code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('material.includesSoundCode','u', 'Material includes sound code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.accessPointLanguage','124', 'Name access point language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.copyToSubjectIndicator','0', 'Name copy to subject indicator');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.subTypeCode','3', 'Name sub type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.typeCode','2', 'Name type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.verificationLevel','2', 'Name verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('name.functionCode','7', 'Name function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.copyToSubjectIndicator','0', 'Title copy to subject indicator');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.accessPointLanguage','124', 'Title access point language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.skipInFiling','0', 'Title skip in filing');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.indexingLanguage','255', 'Title indexing language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.functionCode','1', 'Title function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.secondaryFunctionCode','2', 'Title secondary function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('title.verificationLevel','2', 'Title verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('publisher.accessPointLanguage','124', 'Publisher access point language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('publisher.name','[s.n.]', 'Publisher name');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('publisher.place','[S.l.]', 'Publisher place');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('publisher.verificationLevel','2', 'Publisher verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('publisherAccessPoint.functionCode','24', 'Publisher access point function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subject.accessPointLanguage','255', 'Subject access point language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subject.scriptingLanguage','und', 'Subject scripting language');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subject.sourceCode','6', 'Subject source code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subject.typeCode','19', 'Subject type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subjectAccessPoint.functionCode','3', 'Subject access point function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('subjectAccessPoint.verificationLevel','2', 'Subject access point verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('classification.typeCode','13', 'Classification type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('classificationAccessPoint.functionCode','61', 'Classification access point function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('classification.verificationLevel','2', 'Classification verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('controlNumber.typeCode','9', 'Control number type code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('controlNumberAccessPoint.functionCode','8', 'Control number access point function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('controlNumber.verificationLevel','2', 'Control number verification level');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('control.number.browse.index','16P30', 'Control number browse index');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('nameTitleAccessPoint.functionCode','6', 'Name title access point function code');
Insert into AMICUS.S_SYS_GLBL_VRBL (GLBL_VRBL_NME,GLBL_VRBL_VLU,GLBL_VRBL_NTE) values ('nameTitleAccessPoint.secondaryFunctionCode','2', 'Name title access point secondary function code');
